#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Warehouse")]
	public partial class SQLtoLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKategoria_produktu(Kategoria_produktu instance);
    partial void UpdateKategoria_produktu(Kategoria_produktu instance);
    partial void DeleteKategoria_produktu(Kategoria_produktu instance);
    partial void InsertZamowoienie(Zamowoienie instance);
    partial void UpdateZamowoienie(Zamowoienie instance);
    partial void DeleteZamowoienie(Zamowoienie instance);
    partial void InsertMiejsce_w_mag(Miejsce_w_mag instance);
    partial void UpdateMiejsce_w_mag(Miejsce_w_mag instance);
    partial void DeleteMiejsce_w_mag(Miejsce_w_mag instance);
    partial void InsertProdukt(Produkt instance);
    partial void UpdateProdukt(Produkt instance);
    partial void DeleteProdukt(Produkt instance);
    partial void InsertStan(Stan instance);
    partial void UpdateStan(Stan instance);
    partial void DeleteStan(Stan instance);
    partial void InsertPaleta(Paleta instance);
    partial void UpdatePaleta(Paleta instance);
    partial void DeletePaleta(Paleta instance);
    #endregion
		
		public SQLtoLinqDataContext() : 
				base(global::Warehouse.Properties.Settings.Default.WarehouseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SQLtoLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLtoLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLtoLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLtoLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kategoria_produktu> Kategoria_produktus
		{
			get
			{
				return this.GetTable<Kategoria_produktu>();
			}
		}
		
		public System.Data.Linq.Table<Zamowoienie> Zamowoienies
		{
			get
			{
				return this.GetTable<Zamowoienie>();
			}
		}
		
		public System.Data.Linq.Table<Miejsce_w_mag> Miejsce_w_mags
		{
			get
			{
				return this.GetTable<Miejsce_w_mag>();
			}
		}
		
		public System.Data.Linq.Table<Produkt> Produkts
		{
			get
			{
				return this.GetTable<Produkt>();
			}
		}
		
		public System.Data.Linq.Table<Stan> Stans
		{
			get
			{
				return this.GetTable<Stan>();
			}
		}
		
		public System.Data.Linq.Table<Paleta> Paletas
		{
			get
			{
				return this.GetTable<Paleta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategoria_produktu")]
	public partial class Kategoria_produktu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _nazwa;
		
		private EntitySet<Produkt> _Produkts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    #endregion
		
		public Kategoria_produktu()
		{
			this._Produkts = new EntitySet<Produkt>(new Action<Produkt>(this.attach_Produkts), new Action<Produkt>(this.detach_Produkts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(MAX)")]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoria_produktu_Produkt", Storage="_Produkts", ThisKey="Id", OtherKey="id_kategorii")]
		public EntitySet<Produkt> Produkts
		{
			get
			{
				return this._Produkts;
			}
			set
			{
				this._Produkts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Produkts(Produkt entity)
		{
			this.SendPropertyChanging();
			entity.Kategoria_produktu = this;
		}
		
		private void detach_Produkts(Produkt entity)
		{
			this.SendPropertyChanging();
			entity.Kategoria_produktu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zamowoienie")]
	public partial class Zamowoienie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _id_stanu;
		
		private System.Data.Linq.Binary _nadawca;
		
		private string _odbiorca;
		
		private System.Nullable<System.DateTime> _data_nadania;
		
		private System.Nullable<System.DateTime> _data_odbioru;
		
		private System.Nullable<int> _id_palety;
		
		private EntityRef<Stan> _Stan;
		
		private EntityRef<Paleta> _Paleta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onid_stanuChanging(System.Nullable<int> value);
    partial void Onid_stanuChanged();
    partial void OnnadawcaChanging(System.Data.Linq.Binary value);
    partial void OnnadawcaChanged();
    partial void OnodbiorcaChanging(string value);
    partial void OnodbiorcaChanged();
    partial void Ondata_nadaniaChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_nadaniaChanged();
    partial void Ondata_odbioruChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_odbioruChanged();
    partial void Onid_paletyChanging(System.Nullable<int> value);
    partial void Onid_paletyChanged();
    #endregion
		
		public Zamowoienie()
		{
			this._Stan = default(EntityRef<Stan>);
			this._Paleta = default(EntityRef<Paleta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_stanu", DbType="Int")]
		public System.Nullable<int> id_stanu
		{
			get
			{
				return this._id_stanu;
			}
			set
			{
				if ((this._id_stanu != value))
				{
					if (this._Stan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_stanuChanging(value);
					this.SendPropertyChanging();
					this._id_stanu = value;
					this.SendPropertyChanged("id_stanu");
					this.Onid_stanuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nadawca", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary nadawca
		{
			get
			{
				return this._nadawca;
			}
			set
			{
				if ((this._nadawca != value))
				{
					this.OnnadawcaChanging(value);
					this.SendPropertyChanging();
					this._nadawca = value;
					this.SendPropertyChanged("nadawca");
					this.OnnadawcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odbiorca", DbType="VarChar(MAX)")]
		public string odbiorca
		{
			get
			{
				return this._odbiorca;
			}
			set
			{
				if ((this._odbiorca != value))
				{
					this.OnodbiorcaChanging(value);
					this.SendPropertyChanging();
					this._odbiorca = value;
					this.SendPropertyChanged("odbiorca");
					this.OnodbiorcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nadania", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_nadania
		{
			get
			{
				return this._data_nadania;
			}
			set
			{
				if ((this._data_nadania != value))
				{
					this.Ondata_nadaniaChanging(value);
					this.SendPropertyChanging();
					this._data_nadania = value;
					this.SendPropertyChanged("data_nadania");
					this.Ondata_nadaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_odbioru", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_odbioru
		{
			get
			{
				return this._data_odbioru;
			}
			set
			{
				if ((this._data_odbioru != value))
				{
					this.Ondata_odbioruChanging(value);
					this.SendPropertyChanging();
					this._data_odbioru = value;
					this.SendPropertyChanged("data_odbioru");
					this.Ondata_odbioruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_palety", DbType="Int")]
		public System.Nullable<int> id_palety
		{
			get
			{
				return this._id_palety;
			}
			set
			{
				if ((this._id_palety != value))
				{
					if (this._Paleta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_paletyChanging(value);
					this.SendPropertyChanging();
					this._id_palety = value;
					this.SendPropertyChanged("id_palety");
					this.Onid_paletyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stan_Zamowoienie", Storage="_Stan", ThisKey="id_stanu", OtherKey="Id", IsForeignKey=true)]
		public Stan Stan
		{
			get
			{
				return this._Stan.Entity;
			}
			set
			{
				Stan previousValue = this._Stan.Entity;
				if (((previousValue != value) 
							|| (this._Stan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Stan.Entity = null;
						previousValue.Zamowoienies.Remove(this);
					}
					this._Stan.Entity = value;
					if ((value != null))
					{
						value.Zamowoienies.Add(this);
						this._id_stanu = value.Id;
					}
					else
					{
						this._id_stanu = default(Nullable<int>);
					}
					this.SendPropertyChanged("Stan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paleta1_Zamowoienie", Storage="_Paleta", ThisKey="id_palety", OtherKey="Id", IsForeignKey=true)]
		public Paleta Paleta
		{
			get
			{
				return this._Paleta.Entity;
			}
			set
			{
				Paleta previousValue = this._Paleta.Entity;
				if (((previousValue != value) 
							|| (this._Paleta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paleta.Entity = null;
						previousValue.Zamowoienies.Remove(this);
					}
					this._Paleta.Entity = value;
					if ((value != null))
					{
						value.Zamowoienies.Add(this);
						this._id_palety = value.Id;
					}
					else
					{
						this._id_palety = default(Nullable<int>);
					}
					this.SendPropertyChanged("Paleta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Miejsce_w_mag")]
	public partial class Miejsce_w_mag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _kod;
		
		private EntitySet<Paleta> _Paletas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnkodChanging(string value);
    partial void OnkodChanged();
    #endregion
		
		public Miejsce_w_mag()
		{
			this._Paletas = new EntitySet<Paleta>(new Action<Paleta>(this.attach_Paletas), new Action<Paleta>(this.detach_Paletas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod", DbType="VarChar(MAX)")]
		public string kod
		{
			get
			{
				return this._kod;
			}
			set
			{
				if ((this._kod != value))
				{
					this.OnkodChanging(value);
					this.SendPropertyChanging();
					this._kod = value;
					this.SendPropertyChanged("kod");
					this.OnkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Miejsce_w_mag_Paleta1", Storage="_Paletas", ThisKey="Id", OtherKey="id_miejsca_w_mag")]
		public EntitySet<Paleta> Paletas
		{
			get
			{
				return this._Paletas;
			}
			set
			{
				this._Paletas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Paletas(Paleta entity)
		{
			this.SendPropertyChanging();
			entity.Miejsce_w_mag = this;
		}
		
		private void detach_Paletas(Paleta entity)
		{
			this.SendPropertyChanging();
			entity.Miejsce_w_mag = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produkt")]
	public partial class Produkt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _nazwa;
		
		private System.Nullable<int> _id_kategorii;
		
		private System.Nullable<System.DateTime> _data_przydatnosci;
		
		private System.Nullable<int> _id_palety;
		
		private EntityRef<Kategoria_produktu> _Kategoria_produktu;
		
		private EntityRef<Paleta> _Paleta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void Onid_kategoriiChanging(System.Nullable<int> value);
    partial void Onid_kategoriiChanged();
    partial void Ondata_przydatnosciChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_przydatnosciChanged();
    partial void Onid_paletyChanging(System.Nullable<int> value);
    partial void Onid_paletyChanged();
    #endregion
		
		public Produkt()
		{
			this._Kategoria_produktu = default(EntityRef<Kategoria_produktu>);
			this._Paleta = default(EntityRef<Paleta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(MAX)")]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kategorii", DbType="Int")]
		public System.Nullable<int> id_kategorii
		{
			get
			{
				return this._id_kategorii;
			}
			set
			{
				if ((this._id_kategorii != value))
				{
					if (this._Kategoria_produktu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_kategoriiChanging(value);
					this.SendPropertyChanging();
					this._id_kategorii = value;
					this.SendPropertyChanged("id_kategorii");
					this.Onid_kategoriiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_przydatnosci", DbType="Date")]
		public System.Nullable<System.DateTime> data_przydatnosci
		{
			get
			{
				return this._data_przydatnosci;
			}
			set
			{
				if ((this._data_przydatnosci != value))
				{
					this.Ondata_przydatnosciChanging(value);
					this.SendPropertyChanging();
					this._data_przydatnosci = value;
					this.SendPropertyChanged("data_przydatnosci");
					this.Ondata_przydatnosciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_palety", DbType="Int")]
		public System.Nullable<int> id_palety
		{
			get
			{
				return this._id_palety;
			}
			set
			{
				if ((this._id_palety != value))
				{
					if (this._Paleta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_paletyChanging(value);
					this.SendPropertyChanging();
					this._id_palety = value;
					this.SendPropertyChanged("id_palety");
					this.Onid_paletyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoria_produktu_Produkt", Storage="_Kategoria_produktu", ThisKey="id_kategorii", OtherKey="Id", IsForeignKey=true)]
		public Kategoria_produktu Kategoria_produktu
		{
			get
			{
				return this._Kategoria_produktu.Entity;
			}
			set
			{
				Kategoria_produktu previousValue = this._Kategoria_produktu.Entity;
				if (((previousValue != value) 
							|| (this._Kategoria_produktu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategoria_produktu.Entity = null;
						previousValue.Produkts.Remove(this);
					}
					this._Kategoria_produktu.Entity = value;
					if ((value != null))
					{
						value.Produkts.Add(this);
						this._id_kategorii = value.Id;
					}
					else
					{
						this._id_kategorii = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategoria_produktu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paleta1_Produkt", Storage="_Paleta", ThisKey="id_palety", OtherKey="Id", IsForeignKey=true)]
		public Paleta Paleta
		{
			get
			{
				return this._Paleta.Entity;
			}
			set
			{
				Paleta previousValue = this._Paleta.Entity;
				if (((previousValue != value) 
							|| (this._Paleta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paleta.Entity = null;
						previousValue.Produkts.Remove(this);
					}
					this._Paleta.Entity = value;
					if ((value != null))
					{
						value.Produkts.Add(this);
						this._id_palety = value.Id;
					}
					else
					{
						this._id_palety = default(Nullable<int>);
					}
					this.SendPropertyChanged("Paleta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stan")]
	public partial class Stan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _nazwa_stanu;
		
		private EntitySet<Zamowoienie> _Zamowoienies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onnazwa_stanuChanging(string value);
    partial void Onnazwa_stanuChanged();
    #endregion
		
		public Stan()
		{
			this._Zamowoienies = new EntitySet<Zamowoienie>(new Action<Zamowoienie>(this.attach_Zamowoienies), new Action<Zamowoienie>(this.detach_Zamowoienies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa_stanu", DbType="VarChar(MAX)")]
		public string nazwa_stanu
		{
			get
			{
				return this._nazwa_stanu;
			}
			set
			{
				if ((this._nazwa_stanu != value))
				{
					this.Onnazwa_stanuChanging(value);
					this.SendPropertyChanging();
					this._nazwa_stanu = value;
					this.SendPropertyChanged("nazwa_stanu");
					this.Onnazwa_stanuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stan_Zamowoienie", Storage="_Zamowoienies", ThisKey="Id", OtherKey="id_stanu")]
		public EntitySet<Zamowoienie> Zamowoienies
		{
			get
			{
				return this._Zamowoienies;
			}
			set
			{
				this._Zamowoienies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Zamowoienies(Zamowoienie entity)
		{
			this.SendPropertyChanging();
			entity.Stan = this;
		}
		
		private void detach_Zamowoienies(Zamowoienie entity)
		{
			this.SendPropertyChanging();
			entity.Stan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paleta")]
	public partial class Paleta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _id_miejsca_w_mag;
		
		private string _kod;
		
		private EntitySet<Zamowoienie> _Zamowoienies;
		
		private EntitySet<Produkt> _Produkts;
		
		private EntityRef<Miejsce_w_mag> _Miejsce_w_mag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onid_miejsca_w_magChanging(System.Nullable<int> value);
    partial void Onid_miejsca_w_magChanged();
    partial void OnkodChanging(string value);
    partial void OnkodChanged();
    #endregion
		
		public Paleta()
		{
			this._Zamowoienies = new EntitySet<Zamowoienie>(new Action<Zamowoienie>(this.attach_Zamowoienies), new Action<Zamowoienie>(this.detach_Zamowoienies));
			this._Produkts = new EntitySet<Produkt>(new Action<Produkt>(this.attach_Produkts), new Action<Produkt>(this.detach_Produkts));
			this._Miejsce_w_mag = default(EntityRef<Miejsce_w_mag>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_miejsca_w_mag", DbType="Int")]
		public System.Nullable<int> id_miejsca_w_mag
		{
			get
			{
				return this._id_miejsca_w_mag;
			}
			set
			{
				if ((this._id_miejsca_w_mag != value))
				{
					if (this._Miejsce_w_mag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_miejsca_w_magChanging(value);
					this.SendPropertyChanging();
					this._id_miejsca_w_mag = value;
					this.SendPropertyChanged("id_miejsca_w_mag");
					this.Onid_miejsca_w_magChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod", DbType="VarChar(MAX)")]
		public string kod
		{
			get
			{
				return this._kod;
			}
			set
			{
				if ((this._kod != value))
				{
					this.OnkodChanging(value);
					this.SendPropertyChanging();
					this._kod = value;
					this.SendPropertyChanged("kod");
					this.OnkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paleta1_Zamowoienie", Storage="_Zamowoienies", ThisKey="Id", OtherKey="id_palety")]
		public EntitySet<Zamowoienie> Zamowoienies
		{
			get
			{
				return this._Zamowoienies;
			}
			set
			{
				this._Zamowoienies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paleta1_Produkt", Storage="_Produkts", ThisKey="Id", OtherKey="id_palety")]
		public EntitySet<Produkt> Produkts
		{
			get
			{
				return this._Produkts;
			}
			set
			{
				this._Produkts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Miejsce_w_mag_Paleta1", Storage="_Miejsce_w_mag", ThisKey="id_miejsca_w_mag", OtherKey="Id", IsForeignKey=true)]
		public Miejsce_w_mag Miejsce_w_mag
		{
			get
			{
				return this._Miejsce_w_mag.Entity;
			}
			set
			{
				Miejsce_w_mag previousValue = this._Miejsce_w_mag.Entity;
				if (((previousValue != value) 
							|| (this._Miejsce_w_mag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Miejsce_w_mag.Entity = null;
						previousValue.Paletas.Remove(this);
					}
					this._Miejsce_w_mag.Entity = value;
					if ((value != null))
					{
						value.Paletas.Add(this);
						this._id_miejsca_w_mag = value.Id;
					}
					else
					{
						this._id_miejsca_w_mag = default(Nullable<int>);
					}
					this.SendPropertyChanged("Miejsce_w_mag");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Zamowoienies(Zamowoienie entity)
		{
			this.SendPropertyChanging();
			entity.Paleta = this;
		}
		
		private void detach_Zamowoienies(Zamowoienie entity)
		{
			this.SendPropertyChanging();
			entity.Paleta = null;
		}
		
		private void attach_Produkts(Produkt entity)
		{
			this.SendPropertyChanging();
			entity.Paleta = this;
		}
		
		private void detach_Produkts(Produkt entity)
		{
			this.SendPropertyChanging();
			entity.Paleta = null;
		}
	}
}
#pragma warning restore 1591
